force-app/main/default/objects/FN_Projection__c/FN_Projection__c.object-meta.xml
<CustomObject>
    <description>an agile projection record</description>
    <label>Projection</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FN_Projection__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The project description</description>
    <inlineHelpText>The project description</inlineHelpText>
    <label>Description</label>
    <length>512</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FN_Projection__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related Epic</description>
    <inlineHelpText>The related Epic.  This is used when creating the Work records.</inlineHelpText>
    <label>Epic</label>
    <referenceTo>agf__ADM_Epic__c</referenceTo>
    <relationshipLabel>Projections</relationshipLabel>
    <relationshipName>Projections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FN_Projection__c/fields/ProductTag__c.field-meta.xml
<CustomField>
    <fullName>ProductTag__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The related product tag that will be used for all related project lines that become work items.</description>
    <inlineHelpText>Select the product tag.  The value will be used when creating work items.</inlineHelpText>
    <label>Product Tag</label>
    <referenceTo>agf__ADM_Product_Tag__c</referenceTo>
    <relationshipLabel>Projections</relationshipLabel>
    <relationshipName>Projections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FN_Projection__c/fields/ProjectedDurationWithBuffer__c.field-meta.xml
<CustomField>
    <fullName>ProjectedDurationWithBuffer__c</fullName>
    <description>The projected amount of time in work rate units, including the buffer, to complete the work for this project.</description>
    <inlineHelpText>The projected time, in Work Rate units, to complete the work.</inlineHelpText>
    <label>Projected Duration w/Buffer</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_Projection__c/fields/ProjectionSheet__c.field-meta.xml
<CustomField>
    <fullName>ProjectionSheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projection Sheet</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A Feature record type is the only type that can be linked to a Sheet record type.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Feature</value>
        </filterItems>
        <filterItems>
            <field>FN_Projection__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sheet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FN_Projection__c</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FN_Projection__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>The size of a feature or an entire projection</description>
    <label>Size</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_Projection__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>the status of the project</description>
    <inlineHelpText>the status of the project</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FN_Projection__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>agf__ADM_Scrum_Team__c</referenceTo>
    <relationshipLabel>Projections</relationshipLabel>
    <relationshipName>Projections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FN_Projection__c/fields/WorkType__c.field-meta.xml
<CustomField>
    <fullName>WorkType__c</fullName>
    <label>Work Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SteerCo</fullName>
                <default>true</default>
                <label>SteerCo</label>
            </value>
            <value>
                <fullName>KLO</fullName>
            </value>
            <value>
                <fullName>F&amp;E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FN_ProjectionLine__c/FN_ProjectionLine__c.object-meta.xml
<CustomObject>
    <description>a line item of a projection</description>
    <label>Projection Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projection Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FN_ProjectionLine__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <inlineHelpText>notes/description maps to the new story details field.</inlineHelpText>
    <label>Details</label>
    <length>512</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FN_ProjectionLine__c/fields/Projection__c.field-meta.xml
<CustomField>
    <fullName>Projection__c</fullName>
    <description>The related projection</description>
    <inlineHelpText>The related projection</inlineHelpText>
    <label>Projection</label>
    <referenceTo>FN_Projection__c</referenceTo>
    <relationshipLabel>Projection Lines</relationshipLabel>
    <relationshipName>ProjectionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FN_ProjectionLine__c/fields/WorkItem__c.field-meta.xml
<CustomField>
    <fullName>WorkItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related work item</description>
    <inlineHelpText>The work item that was created from this record</inlineHelpText>
    <label>Work Item</label>
    <referenceTo>agf__ADM_Work__c</referenceTo>
    <relationshipLabel>Projection Lines</relationshipLabel>
    <relationshipName>Projection_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FN_ProjectionLine__c/fields/WorkItemSize__c.field-meta.xml
<CustomField>
    <fullName>WorkItemSize__c</fullName>
    <formula>WorkItem__r.agf__Story_Points__c</formula>
    <label>Work Item Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_ProjectionLine__c/fields/WorkItemStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkItemStatus__c</fullName>
    <description>The related work item&#39;s status</description>
    <formula>TEXT( WorkItem__r.agf__Status__c )</formula>
    <inlineHelpText>The related work item&#39;s status</inlineHelpText>
    <label>Work Item Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FN_ProjectionController.cls
public class FN_ProjectionController {

    @AuraEnabled(Cacheable=true)
    public static agf__ADM_Scrum_Team_Member__c[] searchTeams (String userId) {
       return [
            SELECT agf__Scrum_Team__c,
                    agf__Scrum_Team_Name__c 
            FROM agf__ADM_Scrum_Team_Member__c 
            WHERE agf__Member_Name__c = :userId
        ];
    }

    /**
     * returns a list of all projections for the record type name 'sheet'
     * 
     * Returns:
     *  FN_Projection__c[] - an array of Fifty Ninety Projections
     */
    @AuraEnabled(Cacheable=true)
    public static FN_Projection__c[] getAllProjectionSheets() {
        return [
            SELECT Id, Name, Description__c, RateOfWork__c, Team__c, ProjectedDuration__c, ProjectedDurationWithBuffer__c, Buffer__c,
                Team__r.Name, Status__c, WorkType__c, Epic__r.Name, Epic__r.Id, ProductTag__c, ProductTag__r.Name
            FROM FN_Projection__c 
            WHERE RecordType.Name = 'Sheet' ORDER BY Name
        ];
    }

    /**
     * returns a list of projections with a record type of 'sheet' where the name is like the provided search term
     * Input Params: 
     *  String searchTerm - the string used to match when searching
     * 
     * Returns:
     *  FN_Projection__c[] - an arry of Projections
     */
    @AuraEnabled(Cacheable=true)
    public static FN_Projection__c[] searchProjectionSheets(String searchTerm) {       
        searchTerm = searchTerm.trim();

        // return all projections if searchTerm is null/empty
        if (String.isEmpty(searchTerm)) {
            return getAllProjectionSheets();
            
        } else {
            searchTerm = '%' + searchTerm + '%';
            return [
                SELECT Id, Name, Description__c, RateOfWork__c, Team__c, ProjectedDuration__c, ProjectedDurationWithBuffer__c, Buffer__c,
                    Team__r.Name, Status__c, WorkType__c, Epic__r.Name, Epic__r.Id, ProductTag__c, ProductTag__r.Name
                FROM FN_Projection__c 
                WHERE RecordType.Name = 'Sheet' AND Name LIKE :searchTerm ORDER BY Name LIMIT 50
            ];
        }
    }

    /**
     * returns a list of projection line items for the given projection id
     * 
     * Input Params: 
     *  String projectionId = the projection id used to filter the projection line items.
     * 
     * Returns:
     *  FN_ProjectionLine__c[] - an array of projection line items.
     */
    @AuraEnabled(Cacheable=false)
    public static FN_ProjectionModel getProjectionFeaturesAndLines(string projectionId){
        if(String.isEmpty(projectionId)) {
            return null;
        }

        FN_Projection__c projection = [
            SELECT Id, Name, RecordType.Name, Buffer__c, Description__c, ProjectedDuration__c, ProjectedDurationWithBuffer__c, 
            RateOfWork__c, FeatureOrder__c, Team__r.Name, Epic__r.Name, Epic__r.Id, ProductTag__c,
                (SELECT Id, Name, Projection__c, ItemOrder__c, WorkItemName__c, WorkItemSize__c, WorkItemStatus__c, WorkItem__c, FiftySize__c, NinetySize__c, Details__c
                    FROM ProjectionLines__r
                    ORDER BY ItemOrder__c
                )
            FROM FN_Projection__c
            WHERE Id = :projectionId
        ][0];

        // get the related features with line items
        List<FN_Projection__c> featureLines = [
            SELECT Id, Name, RecordType.Name, Buffer__c, Description__c, ProjectedDuration__c, ProjectedDurationWithBuffer__c, RateOfWork__c, FeatureOrder__c, Epic__r.Name, Epic__r.Id,
                (SELECT ID, Name, Projection__c, ItemOrder__c, WorkItemName__c, WorkItemSize__c, WorkItemStatus__c, WorkItem__c, FiftySize__c, NinetySize__c, Details__c
                    FROM ProjectionLines__r
                    ORDER BY ItemOrder__c
                )
            FROM FN_Projection__c
            WHERE ProjectionSheet__c = :projection.Id
            ORDER BY FeatureOrder__c
        ];
        
        FN_ProjectionModel projectionModel = new FN_ProjectionModel(projection, featureLines);
        return projectionModel;
    }

    /**
     * Creates a new work record and updates the projection line with the newly created work item's ID.
     * 
     * Input Params:
     *  string workRecordTypeId: the record type used to create the work item
     *  string productTagId: the product tag used to create the work item
     *  string projectionLineId: the related projection line for the work item
     *  string name: used to set the subject of the work item
     *  string description: used to set the details of the work item
     *  string epicId: the epic to which the new work item is related
     *  string teamId: the team to which the new work item is related
     * 
     * Returns:
     *  agf__ADM_Work__c: the newly created work item
     */
    @AuraEnabled
    public static FN_ProjectionLine__c createWorkItem(string workRecordTypeId, string productTagId, string projectionLineId, 
                                                    string name, string description, string epicId, string teamId) { 
        agf__ADM_Work__c work = new agf__ADM_Work__c(
            RecordTypeId = workRecordTypeId,
            agf__Product_Tag__c = productTagId,
            agf__Subject__c = name,
            agf__Details__c = description,
            agf__Scrum_Team__c = teamId,
            agf__Epic__c = epicId);
        
        INSERT work;

        FN_ProjectionLine__c line = new FN_ProjectionLine__c (
            Id = projectionLineId,
            WorkItem__c = work.Id
        );
        
        UPDATE line;

        return [SELECT ID, Name, Projection__c, ItemOrder__c, WorkItemName__c, WorkItemSize__c, WorkItemStatus__c, 
                        WorkItem__c, FiftySize__c, NinetySize__c, Details__c
            FROM FN_ProjectionLine__c
            WHERE ID = :projectionLineId
        ];
    }

    @AuraEnabled(cacheable=false)
    public static void calculateProjection(String projectionSheetId) {
        system.debug('calculate starting with id: ' + projectionSheetId);
        // try {
            // get the feature sheet record
            List<FN_Projection__c> projectionSheets = [SELECT Id, RateOfWork__c FROM FN_Projection__c WHERE Id = :projectionSheetId];
            
            // short circuit if the sheet was not found or if the rateOfWork is zero or less.
            if(projectionSheets == null || projectionSheets.size() != 1 || projectionSheets[0].RateOfWork__c < 1) {
                system.debug('did not find the sheet');
                return;
            }

            // get feature and featureItems
            List<FN_Projection__c> features = [
                SELECT ID, Name,
                    (SELECT ID, Name, FiftySize__c, NinetySize__c FROM ProjectionLines__r)
                FROM FN_Projection__c
                WHERE ProjectionSheet__c = :projectionSheetId
            ];

            // short circuit the processing if there are not any projection line items;
            if(features == null || features.size() < 1) {
                system.debug('did not find any features');
                return;
            }
            
            FN_Projection__c sheet = projectionSheets[0];
            Decimal runningFiftySize = 0;
            Decimal runningSquareOfDiffSize = 0;
            List<FN_Projection__c> projectionUpdates = new List<FN_Projection__c>();
            
            // loop features and update the size and buffer values
            for(FN_Projection__c feature : features) {
                system.debug('feature: ' + feature.name);
                Decimal featureFiftySize = 0;
                Decimal featureNinetySize = 0;
                Decimal featureSquareOfDiffSize = 0;

                if(feature.ProjectionLines__r == null || feature.ProjectionLines__r.size() < 1) {
                    system.debug('skipping - no project lines');
                    continue;
                }
                system.debug(feature.Name + ' - featureSquareOfDiffSize: ' + featureSquareOfDiffSize);
                for(FN_ProjectionLine__c line : feature.ProjectionLines__r) {
                    Decimal fiftySize = line.FiftySize__c == null ? 0 : line.FiftySize__c;
                    Decimal ninetySize = line.NinetySize__c == null ? 0 : line.NinetySize__c;
                    featureFiftySize += fiftySize;
                    featureNinetySize += ninetySize;
                    system.debug('square diff: ' + getSquareOfDiff(fiftySize, ninetySize));
                    featureSquareOfDiffSize += getSquareOfDiff(fiftySize, ninetySize);
                }
                system.debug(feature.Name + ' - featureSquareOfDiffSize: ' + featureSquareOfDiffSize);
                runningFiftySize += featureFiftySize;
                runningSquareOfDiffSize += featureSquareOfDiffSize;

                // populate object to update and add to collection
                FN_Projection__c p = new FN_Projection__c (
                    id = feature.Id,
                    Size__c = featureFiftySize,
                    Buffer__c = getBuffer(featureSquareOfDiffSize, sheet.RateOfWork__c)
                );
                projectionUpdates.add(p);
            }

            // get list of line items tied directly to the sheet
            List<FN_ProjectionLine__c> featurelessLines = [
                SELECT ID, Name, FiftySize__c, NinetySize__c 
                FROM FN_ProjectionLine__c
                WHERE projection__c = :sheet.id];

            // loop lines not related to a feature
            for(FN_ProjectionLine__c line : featurelessLines) {
                // add to running total numbers.
                runningFiftySize += line.FiftySize__c == null ? 0 : line.FiftySize__c;
                runningSquareOfDiffSize += getSquareOfDiff(line.fiftySize__c == null ? 0 : line.FiftySize__c, line.NinetySize__c == null ? 0 : line.NinetySize__c);
            }

            system.debug('running 50 size: ' + runningFiftySize);
            system.debug('running diffs^2: ' + runningSquareOfDiffSize);
            //update the sheet totals and add to the projections collection for updating.
            sheet.Size__c = runningFiftySize;
            sheet.Buffer__c = getBuffer(runningSquareOfDiffSize, sheet.RateOfWork__c);
            sheet.ProjectedDuration__c = runningFiftySize / sheet.RateOfWork__c;
            sheet.ProjectedDurationWithBuffer__c = sheet.Buffer__c + sheet.ProjectedDuration__c;
            
            projectionUpdates.add(sheet);

            //update DML
            system.debug('updating');
            UPDATE projectionUpdates;

       // } catch(exception ex) {
       //     throw new ProjectionException(ex.getMessage());
       // }
        
        return;
    }

    public static Decimal getSquareOfDiff(Decimal fiftySize, Decimal ninetySize) {
        if(ninetySize < fiftySize) {
            return 0;
        }

        return (ninetySize - fiftySize).pow(2);
    }

    private static Decimal getBuffer(Decimal squareOfDiffSum, Decimal rate) {
        if(rate < 1) {
            return 0;
        }

        return Math.sqrt(squareOfDiffSum) / rate;
    }

    public class ProjectionException extends Exception {

    }
}