force-app/main/default/objects/FN_Project__c/FN_Project__c.object-meta.xml
<CustomObject>
    <description>a fifty ninety project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FN_Project__c/fields/Buffer__c.field-meta.xml
<CustomField>
    <fullName>Buffer__c</fullName>
    <inlineHelpText>The 50/90 size buffer</inlineHelpText>
    <label>Buffer</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The project description</description>
    <inlineHelpText>The project description</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FN_Project__c/fields/ProjectedTime__c.field-meta.xml
<CustomField>
    <fullName>ProjectedTime__c</fullName>
    <description>The total size of the project based on the project item records</description>
    <label>Projected Time</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_Project__c/fields/ProjectedTimeWithBuffer__c.field-meta.xml
<CustomField>
    <fullName>ProjectedTimeWithBuffer__c</fullName>
    <description>the projected amount of time with the buffer to complete the work for this project</description>
    <inlineHelpText>The projected time to complete the work.</inlineHelpText>
    <label>Projected Time w/Buffer</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_Project__c/fields/ProjectSheet__c.field-meta.xml
<CustomField>
    <fullName>ProjectSheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Sheet</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A Feature record type is the only type that can be linked to a Sheet record type.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Feature</value>
        </filterItems>
        <filterItems>
            <field>FN_Project__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sheet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FN_Project__c</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FN_Project__c/fields/RateOfWork__c.field-meta.xml
<CustomField>
    <fullName>RateOfWork__c</fullName>
    <description>the rate at which work is completed.  could be by points per some time block or number of stories.</description>
    <inlineHelpText>The rate at which the work is completed.  Could be a sprint velocity or points per some other time period.  Could also be the number of stories worked in a given time period.</inlineHelpText>
    <label>Rate of Work</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_Project__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>agf__ADM_Scrum_Team__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FN_Project__c/recordTypes/ProjectSheet.recordType-meta.xml
<RecordType>
    <fullName>ProjectSheet</fullName>
    <active>true</active>
    <description>A new project sheet that contains project line items optionally grouped by feature</description>
    <label>Sheet</label>
</RecordType>

force-app/main/default/objects/FN_ProjectLine__c/FN_ProjectLine__c.object-meta.xml
<CustomObject>
    <description>a line item of a project</description>
    <label>Project Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FN_ProjectLine__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <inlineHelpText>notes/description maps to the new story details field.</inlineHelpText>
    <label>Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FN_ProjectLine__c/fields/FiftySize__c.field-meta.xml
<CustomField>
    <fullName>FiftySize__c</fullName>
    <description>The fifty percent size projected value.  This is the best case scenario.</description>
    <inlineHelpText>The fifty percent size projected value. This is the best case scenario.</inlineHelpText>
    <label>50 Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_ProjectLine__c/fields/ItemOrder__c.field-meta.xml
<CustomField>
    <fullName>ItemOrder__c</fullName>
    <description>The field used to order the items</description>
    <inlineHelpText>The a numeric value used to order the line items.</inlineHelpText>
    <label>Item Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_ProjectLine__c/fields/NinetySize__c.field-meta.xml
<CustomField>
    <fullName>NinetySize__c</fullName>
    <description>The fifty percent size projected value. This is the best case scenario.</description>
    <inlineHelpText>The fifty percent size projected value. This is the best case scenario.</inlineHelpText>
    <label>90 Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FN_ProjectLine__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The related project</description>
    <inlineHelpText>The related project</inlineHelpText>
    <label>Project</label>
    <referenceTo>FN_Project__c</referenceTo>
    <relationshipLabel>Project Lines</relationshipLabel>
    <relationshipName>ProjectLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FN_ProjectLine__c/fields/WorkItem__c.field-meta.xml
<CustomField>
    <fullName>WorkItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related work item</description>
    <inlineHelpText>The work item that was created from this record</inlineHelpText>
    <label>Work Item</label>
    <referenceTo>agf__ADM_Work__c</referenceTo>
    <relationshipLabel>Project Lines</relationshipLabel>
    <relationshipName>Project_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FN_ProjectLine__c/fields/WorkItemName__c.field-meta.xml
<CustomField>
    <fullName>WorkItemName__c</fullName>
    <description>The related work item&#39;s Name</description>
    <formula>WorkItem__r.Name</formula>
    <inlineHelpText>The related work item&#39;s Name</inlineHelpText>
    <label>Work Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FN_ProjectController.cls
public with sharing class FN_ProjectController {

    @AuraEnabled(Cacheable=true)
    public static agf__ADM_Scrum_Team_Member__c[] searchTeams (String userId) {
       return [
            SELECT agf__Scrum_Team__c,
                    agf__Scrum_Team_Name__c 
            FROM agf__ADM_Scrum_Team_Member__c 
            WHERE agf__Member_Name__c = :userId
        ];
    }

    /**
     * returns a list of all projects
     * 
     * Returns:
     *  FN_Project__c[] - an array of Fifty Ninety Projects
     */
    @AuraEnabled(Cacheable=true)
    public static FN_Project__c[] getAllProjectSheets() {
        return [
            SELECT Id, Name, Description__c, RateOfWork__c, Team__c, ProjectedTime__c, ProjectedTimeWithBuffer__c, Buffer__c,
                Team__r.Name
            FROM FN_Project__c 
            WHERE RecordType.Name = 'Sheet' ORDER BY Name
        ];
    }

    /**
     * returns a list of projects where the name is like the provided search term
     * Input Params: 
     *  String searchTerm - the string used to match when searching
     * 
     * Returns:
     *  FN_Project__c[] - an arry of Fifty Ninety Projects
     */
    @AuraEnabled(Cacheable=true)
    public static FN_Project__c[] searchProjectSheets(String searchTerm) {       
        searchTerm = searchTerm.trim();

        // return all projects if searchTerm is null/empty
        if (String.isEmpty(searchTerm)) {
            return getAllProjectSheets();
            
        } else {
            searchTerm = '%' + searchTerm + '%';
            return [
                SELECT Id, Name, Description__c, RateOfWork__c, Team__c, ProjectedTime__c, ProjectedTimeWithBuffer__c, Buffer__c
                    , Team__r.Name
                FROM FN_Project__c 
                WHERE RecordType.Name = 'Sheet' AND Name LIKE :searchTerm ORDER BY Name LIMIT 50
            ];
        }
    }

    /**
     * returns a list of project line items for the given project id
     * 
     * Input Params: 
     *  String projectId = the project id used to filter the project line items.
     * 
     * Returns:
     *  FN_ProjectLine__c[] - an array of project line items.
     */
    @AuraEnabled(Cacheable=false)
    public static FN_Project__c getProjectFeaturesAndLines(string projectId){
        if(String.isEmpty(projectId)) {
            return null;
        }

        FN_Project__c projectSheet = [
            SELECT Id, Name, RecordType.Name, Buffer__c, Description__c, ProjectedTime__c, ProjectedTimeWithBuffer__c, RateOfWork__c, Team__r.Name,
                (SELECT Id, Name, RecordType.Name, Buffer__c, Description__c, ProjectedTime__c, ProjectedTimeWithBuffer__c, RateOfWork__c
                    FROM Features__r
                ),
                (SELECT Id, Name FROM ProjectLines__r ORDER BY ItemOrder__c)
            FROM FN_Project__c
            WHERE Id = :projectId
        ][0];
        system.debug('project Sheet');
        system.debug(projectSheet);

        // get a list of feature IDs in order to get the related line items.
        Map<Id, integer> featureIdsMap = new Map<Id, integer>();
        for(Integer idx = 0; idx < projectSheet.Features__r.size(); idx++) {
            featureIdsMap.put(projectSheet.Features__r[idx].Id, idx);
        }

        // get the realted line items
        List<FN_ProjectLine__c> featureLines = [
            SELECT ID, Name, Project__c, ItemOrder__c, WorkItemName__c, WorkItemSize__c, WorkItemStatus__c, WorkItem__c, FiftySize__c, NinetySize__c, Details__c
            FROM FN_ProjectLine__c
            WHERE ID in :featureIdsMap.KeySet()
            ORDER BY Project__c, ItemOrder__c
        ];

        // loop the feature lines and add them to the lines collection of the related feature using the previously populated map to find the correct index
        for(FN_ProjectLine__c line : featureLines) {
            projectSheet.Features__r[featureIdsMap.get(line.Project__c)].ProjectLines__r.add(line);
        }

        return projectSheet;
    }
}